### ISSUE TITLE
Version 2.6.1 (1230) Not working

### ISSUE THREAD

**Issue by kosbarts** [Mark2Mark/Synced-Tabs#6]
Hi Mark,

the plugin stopped working in Version 2.6.1 (1230).

I am still on Sierra 10.12.6

K.

**Comment by Mark2Mark** [comment]
Is there anything written in the bottom half of the macro panel?

**Comment by kosbarts** [comment]
Traceback (most recent call last):
  File "plugin.py", line 99, in SyncEditViews
    sourceVisibleRect = sourceTab.viewPort
TypeError: 'int' object is not callable

Traceback (most recent call last):
  File "plugin.py", line 99, in SyncEditViews
    sourceVisibleRect = sourceTab.viewPort
TypeError: 'int' object is not callable

**Comment by schriftgestalt** [comment]
this error is strange. On line 99, no object is called??
